# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Datawire Docs: The Microservices Playbook'
description: 'The Microservices Playbook'
permalink: pretty

collections:
  playbook:
    output: true
    permalink: /:collection/:path/

# Build settings
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
